/* eslint-disable react/no-unescaped-entities */
/*
  Fetching data is done on the Layout componet and pass via 
  React.cloneElement module 'children' prop. The 'children' prop
  render the pages to the Layout components. 
*/

import { Fragment, useEffect, useState, cloneElement } from "react";
import { getPodcastSeries, graphQLRequest } from "@/graphQL/gql";
import Head from "next/head";
import Nav from "./nav";
import Footer from "./footer";

export default function Layout({ children }: any) {
  const [podcastSeries, setPodcastSeries] = useState();
  const [error, setError] = useState(false);

  useEffect(() => {
    const componentIsMounted = true;

    async function fetchPodcastSeries() {
      try {
        const { getPodcastSeries: data } = await graphQLRequest(
          getPodcastSeries
        );
        if (componentIsMounted) setPodcastSeries(data);
      } catch (error) {
        if (componentIsMounted) setError(true);
      }
    }
    fetchPodcastSeries();
  }, []);

  if (error) {
    return (
      <main className="h-screen">
        <Head>
          <title>Larks Podcast | Error</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
       <div id="network-error-prompt" className="h-full flex justify-center mt-[25rem] p">
       <p className="custom-text-color-primary text-2xl sm:text-4xl mx-10 md:mx-20 lg:mx-[15rem] text-center leading-tight">
          There seem to be a network error! Check that you're connected
          to the internet or try again later
        </p>
       </div>
      </main>
    );
  }

  if (podcastSeries === undefined) {
    return (
      <main className="h-screen">
        <Head>
          <title>Larks Podcast | Loading...</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div
          id="loader-container"
          className="h-full flex justify-center items-center"
        >
          <span className="loader"></span>
        </div>
      </main>
    );
  }

  return (
    <Fragment>
      <Head>
        <title>Larks Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      {podcastSeries !== undefined
        ? cloneElement(children, {
            podcastSeries: podcastSeries,
          })
        : children}
      <Footer />
    </Fragment>
  );
}
