/*
  Fetching data is done on the Layout componet and pass via 
  React.cloneElement module 'children' prop. The 'children' prop
  render the pages to the Layout components. 
*/

import { Fragment, useEffect, useState, cloneElement } from "react";
import { getPodcastSeries, graphQLRequest } from "@/graphQL/gql";
import Head from "next/head";
import Nav from "./nav";
import Footer from "./footer";

export default function Layout({ children }: any) {
  const [podcastSeries, setPodcastSeries] = useState();
  const [error, setError] = useState(false);

  useEffect(() => {
    const componentIsMounted = true;

    async function fetchPodcastSeries() {
      try {
        const {getPodcastSeries: data} = await graphQLRequest(getPodcastSeries);
        if (componentIsMounted) setPodcastSeries(data);
      } catch (error) {
        if (componentIsMounted) setError(true);
      }
    }
    fetchPodcastSeries();
  }, []);

  if (error) {
    return (
      <div>
        <Head>
          <title>Larks Podcast | Error</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>There seem to be an error. Please refresh your browser</p>
      </div>
    );
  }

  if (podcastSeries === undefined) {
    return (
      <div>
        <Head>
          <title>Larks Podcast | Loading...</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>Loading...</p>
      </div>
    )
  }

  return (
    <Fragment>
      <Head>
        <title>Larks Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      {podcastSeries !== undefined ? cloneElement(children, {
        podcastSeries: podcastSeries
      }):children}
      <Footer />
    </Fragment>
  );
}
