import { Fragment } from "react";
import Head from "next/head";
import Nav from "./nav";
import Footer from "./footer";

export default function Layout({ children }: any) {
  return (
    <Fragment>
      <Head>
        <title>Larks Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      {children}
      <Footer />
    </Fragment>
  );
}
